apiVersion: v1
kind: Service
metadata:
  name: ticket-api
spec:
  type: NodePort
  selector: {app: ticket-api}
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
